- name: Check initial topology connectivity
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    cml_host: "{{ lookup('ansible.builtin.env', 'CML_HOST') }}" #192.168.4[.149
    cml_username: "{{ lookup('ansible.builtin.env', 'CML_USERNAME') }}" # admin
    cml_password: "{{ lookup('ansible.builtin.env', 'CML_PASSWORD') }}"
    cml_lab: "{{ lookup('ansible.builtin.env', 'CML_LAB') }}" #workdammit
    
  tasks:
    - name: Get facts about a lab in CML
      cisco.cml.cml_lab_facts:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
      register: results

    - debug:
        var: results
