---
all:
  children:
   core_routers:
     vars:
       ansible_user: cisco
       ansible_ssh_pass: cisco
       ansible_network_os: ios
       ansible_connection: network_cli
     hosts:
       core-0:
         ansible_host: 10.0.0.82

   edge_routers:
     vars:
       ansible_user: cisco
       ansible_ssh_pass: cisco
       ansible_network_os: ios
       ansible_connection: network_cli
     hosts:
       edge-0:
         ansible_host: 172.20.0.2
       edge-1:
         ansible_host: 172.20.0.6

   linux_boxes:
     vars:
       ansible_user: cisco
       ansible_ssh_pass: cisco
       ansible_connection: ssh
     hosts:
       alpine-0:
         ansible_host: 172.20.1.11
       alpine-1:
         ansible_host: 172.20.2.11
