---
- name: Network Commands by Vendor
  hosts: edge-0
  gather_facts: no
  become: yes
  ansible_become_method: enable

  tasks:
  - name: Run an agnostic command
    cli_command:
      command: "show run"
    register: results

  - name: show results
    debug:
      var: results
