- name: Build the topology in Cisco Modeling Labs
  hosts: localhost
  gather_facts: no

  vars:
    cml_host: "{{ lookup('env', 'CML_HOST') }}"
    cml_username: "{{ lookup('env', 'CML_USERNAME') }}"
    cml_password: "{{ lookup('env', 'CML_PASSWORD') }}"
    cml_lab: "{{ lookup('env', 'CML_LAB') }}"
    cml_lab_file: "{{ lookup('env', 'CML_LAB_FILE') }}" 
    hereorthere: present

  tasks:
    # this task is checking to see if the file we're using exists!
    - name: Check for the lab file
      stat:
        path: "{{ cml_lab_file }}"
      register: stat_result

   # this task is asserting that we have everything we need to connect to CML
   # if any of these assertions are false, we'll receive an error message.
    - assert:
        that:
          - stat_result.stat.exists
          - cml_host != ""
          - cml_username != ""
          - cml_password != ""
          - cml_lab != ""
        msg: "CML host, credentials, and topology file are required. Verify the requirements in README are met."

    # this task will push the topology file we wrote and build it in a new CML lab
    - name: Manage the lab in CML
      cisco.cml.cml_lab:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        file: "{{ cml_lab_file }}"
        state: "{{ hereorthere }}"
      register: results

    # this task isn't really relevant right now... it's telling ansible to re-check
    # what labs exist in CML (now that we've created a new one)
    - name: Refresh Inventory
      meta: refresh_inventory
