---
- name: Push Configuration Changes to Network Device
  hosts: "{{ target }}"
  gather_facts: no
  vars:
    changes_file_path: "./router-configs/{{ target }}/change.txt"

  tasks:
    - name: Check if changes.txt exists
      ansible.builtin.stat:
        path: "{{ changes_file_path }}"
      register: changes_file

    - name: Apply configuration from changes.txt if it exists
      when: changes_file.stat.exists
      cisco.ios.ios_config:
        src: "{{ changes_file_path }}"
      notify: 
        - Show push result

  handlers:
    - name: Show push result
      debug:
        msg: "Configuration pushed successfully."
